# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/android.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/linux-static.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/windows.yml
      - /gitlab-templates/windows-static.yml
      - /gitlab-templates/flatpak.yml
