# The current ECM version of this depends on Qt5
function(ecm_generate_pri_file)
endfunction()

# install locations depend on ECMQueryQMake, which depends on Qt5
set(KDE_INSTALL_BINDIR "bin")
set(KDE_INSTALL_LIBDIR "lib")
set(KDE_INSTALL_INCLUDEDIR "include")
set(KDE_INSTALL_CMAKEPACKAGEDIR "${KDE_INSTALL_LIBDIR}/cmake")

set(KDE_INSTALL_TARGETS_DEFAULT_ARGS
    RUNTIME DESTINATION ${KDE_INSTALL_BINDIR}
    LIBRARY DESTINATION ${KDE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${KDE_INSTALL_LIBDIR} COMPONENT Devel
    BUNDLE DESTINATION ${KDE_INSTALL_BUNDLEDIR}
)
